language: node_js

node_js: stable

script:
  - npm install
  - hexo cl

after_success:
  - git config --global user.name "szhgoldeneye"
  - git config --global user.email "szhgoldeneye"
  - sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
  - hexo deploy -g