anguage: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "szhgoldeneye"
  - git config user.email "szhgoldeneye@hotmail.com"
  - git add .
  - git commit -m "Update - auto deploy by Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
  global:
    - GH_REF: github.com/szhgoldeneye/szhgoldeneye.github.io.git